# Generated by Django 3.2.4 on 2023-10-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='pacontraseña',
            new_name='contraseña',
        ),
    ]
