# Generated by Django 3.2.4 on 2023-10-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pacontraseña_registros_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
