# Generated by Django 3.2.4 on 2023-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contraseña_registros_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta_1', models.CharField(max_length=100)),
                ('Pregunta_2', models.CharField(max_length=100)),
                ('Pregunta_3', models.CharField(max_length=100)),
                ('Pregunta_4', models.CharField(max_length=100)),
                ('Pregunta_5', models.CharField(max_length=100)),
                ('Pregunta_6', models.CharField(max_length=100)),
                ('Pregunta_7', models.CharField(max_length=100)),
                ('Pregunta_8', models.CharField(max_length=100)),
                ('Pregunta_9', models.CharField(max_length=100)),
                ('Pregunta_10', models.CharField(max_length=100)),
            ],
        ),
    ]
