# Generated by Django 3.2.4 on 2023-10-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_1',
            new_name='pregunta_1',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_10',
            new_name='pregunta_10',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_2',
            new_name='pregunta_2',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_3',
            new_name='pregunta_3',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_4',
            new_name='pregunta_4',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_5',
            new_name='pregunta_5',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_6',
            new_name='pregunta_6',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_7',
            new_name='pregunta_7',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_8',
            new_name='pregunta_8',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='Pregunta_9',
            new_name='pregunta_9',
        ),
    ]
